# Generated by Django 2.2.6 on 2019-12-17 09:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=12, unique=True)),
                ('detail', models.TextField(default=None)),
                ('threhold', models.IntegerField(default=2)),
                ('normal_price', models.FloatField()),
                ('others', models.ManyToManyField(blank=True, related_name='_category_others_+', to='app.Category')),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=40)),
                ('famillyname', models.CharField(max_length=40)),
                ('mail', models.EmailField(max_length=254)),
                ('cp', models.CharField(max_length=5)),
                ('date_signup', models.DateField(auto_now_add=True)),
                ('admin', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sn', models.CharField(max_length=8, unique=True)),
                ('date_buy', models.DateField(auto_now_add=True)),
                ('is_available', models.BooleanField(default=True)),
                ('buy_price', models.FloatField(default=0.0)),
                ('buy_sn', models.CharField(max_length=8, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PaymentMethod',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method', models.CharField(max_length=30)),
                ('short_method', models.CharField(max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='Phone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(max_length=40, unique=True)),
                ('detail', models.TextField(default=None)),
            ],
        ),
        migrations.CreateModel(
            name='Photos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.CharField(default='default.png', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Repair',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_add', models.DateField(auto_now_add=True)),
                ('date_repaired', models.DateField(blank=True)),
                ('phone_password', models.CharField(blank=True, max_length=20, null=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app.Customer')),
            ],
        ),
        migrations.CreateModel(
            name='RepairState',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(max_length=30)),
                ('short_state', models.CharField(max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='TokenManager',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Token',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=50)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RepairPhoto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caption', models.CharField(max_length=50)),
                ('photo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Photos')),
                ('repair', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Repair')),
            ],
        ),
        migrations.CreateModel(
            name='RepairPayment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
                ('date_paid', models.DateField(blank=True)),
                ('id_payment', models.CharField(max_length=8, unique=True)),
                ('method', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.PaymentMethod')),
                ('repair', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Repair')),
            ],
        ),
        migrations.AddField(
            model_name='repair',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.RepairState'),
        ),
        migrations.CreateModel(
            name='PhoneNumber',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no_phone', models.CharField(max_length=20)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Customer')),
            ],
        ),
        migrations.CreateModel(
            name='CategoryItemPhoneRepair',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('custom_price', models.FloatField(blank=True, default=0.0)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Category')),
                ('item', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app.Item')),
                ('phone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Phone')),
                ('repair', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.Repair')),
            ],
        ),
        migrations.AddField(
            model_name='category',
            name='phone',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Phone'),
        ),
        migrations.AddField(
            model_name='category',
            name='photo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app.Photos'),
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no', models.CharField(max_length=10)),
                ('street', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=50)),
                ('state', models.CharField(blank=True, max_length=50, null=True)),
                ('cp', models.CharField(max_length=5)),
                ('country', models.CharField(default='France', max_length=20)),
                ('label', models.CharField(max_length=25)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Customer')),
            ],
        ),
    ]
