# Generated by Django 2.2.6 on 2019-12-17 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='label',
            field=models.CharField(max_length=25, null=True),
        ),
    ]
