# Generated by Django 2.2.6 on 2019-10-16 14:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_customer_is_admin'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='lastname',
            new_name='firstname',
        ),
    ]
