# Generated by Django 2.2.6 on 2019-12-17 10:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_remove_address_label'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period', models.CharField(default=2019, max_length=6)),
                ('repair', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Repair')),
            ],
        ),
    ]
