# Generated by Django 2.2.6 on 2019-12-17 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_invoice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='repairpayment',
            name='amount',
            field=models.CharField(max_length=20),
        ),
    ]
