# Generated by Django 2.2.6 on 2019-10-16 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20191016_1441'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sn', models.CharField(max_length=4, unique=True)),
                ('date_buy', models.DateField(auto_now_add=True)),
                ('is_available', models.BooleanField(default=True)),
                ('buy_price', models.FloatField(default=0.0)),
            ],
        ),
        migrations.CreateModel(
            name='Phone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(max_length=40, unique=True)),
                ('detail', models.TextField(default=None)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=12, unique=True)),
                ('detail', models.TextField(default=None)),
                ('threhold', models.IntegerField(default=2)),
                ('others', models.ManyToManyField(related_name='_category_others_+', to='app.Category')),
            ],
        ),
    ]
