# Generated by Django 2.2.6 on 2019-12-17 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20191217_1108'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='due',
            field=models.CharField(default=0, max_length=20),
            preserve_default=False,
        ),
    ]
