# Generated by Django 2.2.6 on 2019-10-16 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_category_item_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='others',
            field=models.ManyToManyField(null=True, related_name='_category_others_+', to='app.Category'),
        ),
    ]
