# Generated by Django 2.2.6 on 2019-12-18 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_invoice_due'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='is_on_invoice',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
    ]
