# Generated by Django 2.2.6 on 2019-10-16 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20191016_1505'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='others',
            field=models.ManyToManyField(blank=True, related_name='_category_others_+', to='app.Category'),
        ),
    ]
