# Generated by Django 2.2.6 on 2019-10-16 21:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0008_categoryitemphone'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryItemPhoneRepair',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Repair',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_add', models.DateField(auto_now_add=True)),
                ('date_repaired', models.DateField(blank=True)),
                ('date_paid', models.DateField(blank=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='customer',
            name='is_admin',
        ),
        migrations.AddField(
            model_name='customer',
            name='admin',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='customer',
            name='cp',
            field=models.CharField(default='05000', max_length=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customer',
            name='date_signup',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customer',
            name='mail',
            field=models.EmailField(default='test@test.fr', max_length=254),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='CategoryItemPhone',
        ),
        migrations.AddField(
            model_name='repair',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app.Customer'),
        ),
        migrations.AddField(
            model_name='categoryitemphonerepair',
            name='Repair',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.Repair'),
        ),
        migrations.AddField(
            model_name='categoryitemphonerepair',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Category'),
        ),
        migrations.AddField(
            model_name='categoryitemphonerepair',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Item'),
        ),
        migrations.AddField(
            model_name='categoryitemphonerepair',
            name='phone',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Phone'),
        ),
    ]
