# Generated by Django 2.2.6 on 2019-12-19 22:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20191219_2159'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='others',
        ),
        migrations.AddField(
            model_name='category',
            name='others',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='app.Category'),
        ),
    ]
