# Generated by Django 2.2.6 on 2020-01-09 17:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_auto_20191219_2211'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='others',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='oth', related_query_name='oth', to='app.Category'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='period',
            field=models.CharField(default=2020, max_length=6),
        ),
        migrations.AlterField(
            model_name='repair',
            name='date_add',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='repair',
            name='date_repaired',
            field=models.DateField(blank=True, null=True),
        ),
    ]
