# Generated by Django 2.2.6 on 2020-01-13 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_auto_20200113_1053'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='buy_sn',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
