# Generated by Django 2.2.6 on 2020-01-15 22:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0017_quotation_quotationdetail'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotation',
            name='repair',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.Repair'),
        ),
        migrations.CreateModel(
            name='RepairCaption',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caption', models.TextField(default=None)),
                ('repair', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Repair')),
                ('repairer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
