# Generated by Django 2.2.6 on 2020-01-15 22:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_auto_20200115_2221'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotationdetail',
            name='sell_price',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='quotationdetail',
            name='sell_promo',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='app.Promo'),
            preserve_default=False,
        ),
    ]
