# Generated by Django 2.2.6 on 2020-01-24 11:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_frenchaddress_repairnote'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='threhold',
            new_name='threshold',
        ),
    ]
