# Generated by Django 2.2.6 on 2020-01-27 14:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_auto_20200124_1114'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categoryitemphonerepair',
            name='phone',
        ),
    ]
